apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: file-converter
type: Opaque
data:
  rootUser: bWluaW9hZG1pbg==
  rootPassword: bWluaW9hZG1pbjEyMw==
---
# MinIO runs on 4 nodes (master + 3 RPi workers) for distributed storage
# Optimized for Raspberry Pi with lower resource usage
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: file-converter
spec:
  serviceName: minio-headless
  podManagementPolicy: Parallel
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: minio
              topologyKey: kubernetes.io/hostname
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-01-16T16-07-38Z
          args:
            - server
            - http://minio-{0...3}.minio-headless.file-converter.svc.cluster.local/data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: rootPassword
            - name: MINIO_DISTRIBUTED_MODE_ENABLED
              value: "yes"
            - name: MINIO_DISTRIBUTED_NODES
              value: "4"
            # Pi optimization - reduce resource usage
            - name: MINIO_API_REQUESTS_MAX
              value: "16"
            - name: MINIO_API_REQUESTS_DEADLINE
              value: "10s"
            - name: MINIO_API_CLUSTER_DEADLINE
              value: "10s"
            - name: MINIO_API_CORS_ALLOW_ORIGIN
              value: "*"
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: "public"
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: file-converter
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: file-converter
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
---
# Job to create bucket after MinIO is ready
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  namespace: file-converter
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              sleep 60
              mc alias set myminio http://minio:9000 minioadmin minioadmin123
              mc mb myminio/file-converter --ignore-existing
              mc anonymous set public myminio/file-converter
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
