# Job Manager - runs on master (8GB RPi)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-manager
  namespace: file-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-manager
  template:
    metadata:
      labels:
        app: job-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: job-manager
          image: giangma/fileconverter:job-manager-v2.4
          command: ["/bin/sh", "-c"]
          args:
            - |
              sed -i 's|@app.post("/upload")|@app.post("/api/upload")\n@app.post("/upload")|; s|@app.get("/health")|@app.get("/api/health")\n@app.get("/health")|; s|@app.get("/status/|@app.get("/api/status/|g; s|@app.get("/download/|@app.get("/api/download/|g; s|@app.get("/session/jobs")|@app.get("/api/session/jobs")\n@app.get("/session/jobs")|' /app/main.py
              exec python main.py
          ports:
            - containerPort: 8010
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8010
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8010
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: job-manager
  namespace: file-converter
spec:
  selector:
    app: job-manager
  ports:
    - port: 8000
      targetPort: 8010
