# PDF-DOCX Service - Low resources per pod, scales horizontally
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-docx-service
  namespace: file-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-docx-service
  template:
    metadata:
      labels:
        app: pdf-docx-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: pdf-docx-service
                topologyKey: kubernetes.io/hostname
      containers:
        - name: pdf-docx-service
          image: giangma/fileconverter:pdf-docx-service-v2.1
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: postgres-secret
          env:
            - name: CONVERSION_WORKERS
              value: "1"
            - name: CONVERSION_TIMEOUT
              value: "300"
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-docx-service
  namespace: file-converter
spec:
  selector:
    app: pdf-docx-service
  ports:
    - port: 8002
      targetPort: 8002
